### PR TITLE
WIP: Update embedded-hal to version 1.0.0-alpha.6

### PR DESCRIPTION
**Pull request by caemor**
The delay update is pretty straightforward. 

The error update is more difficult: The current implementation creates a new struct including a single element: the upstream linux error, and implement the e-h error trait for it. I've got two issues with this.
Is creating a new struct the best way to do this?
For matching the e-h trait kind: Currently I just matched everything to `Other` because I couldn't find any good matches when taking a quick glance.  Is there something that should be matched?
The creation of a central error enum for linux e-h would be an other alternative way to solve this.

### CODE REVIEW

**Review by eldruin — COMMENTED** [review]
Nice, thank you for this PR!
The important part would be extracting information from the underlying `nix`/`io` errors in the `embedded_hal::*::Error` implementations so that they can be converted to a meaningful `embedded_hal::*::ErrorKind`.
Converting all errors to `Other` would render all drivers unable to act on things like `i2c::NoAcknowledge`.
For this one needs to dig a bit into the Linux kernel, and so on, though.

As for the error struct itself, in order to be able to implement the traits you already highlighted the possibilities:
1. Wrapper `struct` with the error instance.
2. Wrapper tuple with the error instance.
3. Central `enum`.
3.1. With variants per protocol
3.2. Flat with all variants in one level

I think 2 looks simpler than 1 but the code would look weirder with the `.0`s so I think 1 would read better. Whether the inner element should be called `err` `error`, `inner` or something else, I am not sure. Probably any.
I think 3 would be more complex to implement.
3.1. Would definitely more cumbersome to match for the user, as non-relevant variants would need to be matched as well (e.g. spi error variant on i2c operations).
3.2. Seems very unpractical and confusing to match for the user.
All in all, I think the current 2 approach is the right one.

**Comment by caemor** [comment]
If someone else wants to take over, go for it. I am currently missing the time to finish this.

**Comment by ryankurte** [comment]
it doesn't look to me like any of the `IoErrorKind`s have great correspondence with our `ErrorKind`s except for I2C, see changes [here](https://github.com/rust-embedded/linux-embedded-hal/commit/066c10255008c1d47f138e0423286c9a698fefd7) to match that. i'd be happy to merge this then that and keep moving forward, any other opinions @rust-embedded/embedded-linux ?

**Comment by eldruin** [comment]
Ok, Let's merge this then and I will create an issue about improving the match.
@caemor could you resolve the conflict?

**Review by eldruin — APPROVED** [review]
Thank you!
bors r+

**Comment by ryankurte** [comment]
thanks folks! @eldruin what do you think of another alpha release to keep up with e-h?

**Comment by eldruin** [comment]
Sure. I would prefer doing #74 beforehand, though.

**Pull request merged**
