### PR TITLE
Added input pin impl (requires unproven hal trait)

### PR DESCRIPTION
**Pull request by ryankurte**
Do we have opinions on the use of `unproven` traits in this library?

### CODE REVIEW

**Comment by ryankurte** [comment]
bors try

**Comment by therealprof** [comment]
@ryankurte Well, you could submit a PR to close https://github.com/rust-embedded/embedded-hal/issues/41 . ;)

**Comment by ryankurte** [comment]
@therealprof I considered that but it would seem impolite to land it before @eldruin's https://github.com/rust-embedded/embedded-hal/pull/97

**Comment by therealprof** [comment]
@ryankurte As mentioned in the PR you just closed, I do see them as two separate topics. Making this unproven does not preclude making it fallible since this will end up in two different (incompatible) HAL versions anyway.

**Comment by Caemor** [comment]
Would it be possible to release and accept this PR as the embedded hal discussion seems to still need a bit more time?

**Pull request merged**
