### PR TITLE
Adapt to embedded-hal-1.0.0-alpha.2

### PR DESCRIPTION
**Pull request by eldruin**
Builds on and superseeds #43

### CODE REVIEW

**Comment by ryankurte** [comment]
I've created a `v0.3.x` branch for ongoing maintenance of these releases, happy to land this on `master` for alpha releases now @posborne ?

**Comment by ryankurte** [comment]
@eldruin could you please update the changelog? then i can approve this / land #49 and ship an alpha ^_^

**Comment by eldruin** [comment]
@ryankurte done, thanks!

**Review by ryankurte — APPROVED** [review]
lgtm, thanks!

bors r+

**Comment by eldruin** [comment]
Closing in favour of #50

**Pull request closed without merging**
