### PR TITLE
Update embedded-hal to 1.0.0-alpha.8

### PR DESCRIPTION
**Pull request by kelnos**

### CODE REVIEW

**Comment by har7an** [comment]
Hello,

is there any progress on this?

**Comment by eldruin** [comment]
Thanks for the reminder.
Updating the MSRV to version 1.54.0 would make sense, since that is the version that `embedded-hal` 1.0 will have (at this time, may increase further).

**Comment by kelnos** [comment]
Ok, 1.54.0 it is!

**Comment by eldruin** [comment]
Thanks!
Could you also update the MSRV in the [bors.toml](https://github.com/rust-embedded/linux-embedded-hal/blob/master/.github/bors.toml) file? otherwise this will not merge

**Comment by kelnos** [comment]
> Could you also update the MSRV in the [bors.toml](https://github.com/rust-embedded/linux-embedded-hal/blob/master/.github/bors.toml) file? otherwise this will not merge

Done!

**Review by eldruin — COMMENTED** [review]
Alright, this looks good to me, although the `transfer_in_place` is actually fake since it copies the buffer.
We could also add the small piece of unsafe code we had back some day if this is a problem for somebody, though.
Could you also add an entry to the changelog?

**Comment by kelnos** [comment]
> Could you also add an entry to the changelog?

Done

**Review by eldruin — APPROVED** [review]
Thank you!
bors r+

**Pull request merged**
