### PR TITLE
Add github actions CI

### PR DESCRIPTION
**Pull request by ryankurte**
Replaces #56, just adding the actions executor without swapping bors or removing travis.

Odds are this doesn't work but, seemingly one can't add actions to a repo from a branch so it has to be manually merged anyway and fixed in PRs...

@posborne seem (un)reasonable?

### CODE REVIEW

**Comment by ryankurte** [comment]
bors try

**Comment by eldruin** [comment]
rustfmt seems to have failed. Could you fix that @ryankurte?

**Comment by ryankurte** [comment]
huh, looks like actions is now executing and i'm not sure what changed?

applied rustfmt, fingers crossed...

**Review by eldruin — DISMISSED** [review]
Looks good to me, thanks!

bors r+

**Comment by eldruin** [comment]
bors retry

**Comment by eldruin** [comment]
bors retry

**Comment by eldruin** [comment]
@ryankurte Since this works fine, could you also remove the `.travis.yml` file and update the `bors.toml` to have the correct names from GHA like [here](https://github.com/rust-embedded/embedded-hal/blob/master/.github/bors.toml)
I really can't wait to get rid of Travis....

**Comment by ryankurte** [comment]
bors try

**Review by eldruin — APPROVED** [review]
Great, thanks!

bors r+

**Comment by eldruin** [comment]
Finally! :tada:

**Pull request merged**
