### PR TITLE
Update for release v0.4.0-alpha.0

### PR DESCRIPTION
**Pull request by ryankurte**

### CODE REVIEW

**Comment by ryankurte** [comment]
hey @posborne had a chance to look at this?

**Review by posborne — APPROVED** [review]
LGTM

bors r+

**Comment by ryankurte** [comment]
bors retry

**Comment by ryankurte** [comment]
tagged and released to [crates.io](https://crates.io/crates/linux-embedded-hal/0.4.0-alpha.0)

**Pull request merged**
