### PR TITLE
Update embedded-hal to version 1.0.0-alpha.5

### PR DESCRIPTION
**Pull request by eldruin**
I will add support for embedded-hal 0.2.x in parallel as described [here](https://github.com/rust-embedded/embedded-hal#adding-support-for-an-embedded-hal--alpha-version-in-a-hal-implementation). This PR contains some preparation for that.

### CODE REVIEW

**Comment by eldruin** [comment]
It seems the MSRV build is broken because `bitflags` updated their MSRV. The same thing should happen for `spidev`, `i2cdev` and `gpio-cdev`.

**Comment by eldruin** [comment]
Alright, I have updated the MSRV and as well as `gpio-cdev`, `spidev` and `i2cdev` to their newly-released versions.
bors try

**Comment by ryankurte** [comment]
hey thanks for your work! i've updated [embedded-hal-compat](https://github.com/ryankurte/embedded-hal-compat) to `1.0.0-alpha.5`, maybe y'all disagree but my preference would be to provide backwards compat separately via that than to double the work / loc for the HALs? (and if that's the case, we could update [this](https://github.com/rust-embedded/embedded-hal#adding-support-for-an-embedded-hal--alpha-version-in-a-hal-implementation) to match)

**Comment by eldruin** [comment]
That is also a possibility. That would certainly do away with the concern of how long should we support 0.2.x in HALs and what that means for SemVer. Since removing it would be a breaking change, it may be better not to do it at all.
Anyway, that would be an addition and I think we should merge this and release a 0.4.0-alpha.1

**Comment by eldruin** [comment]
bors try

**Review by ryankurte — APPROVED** [review]
(s|l)gtm, thanks!

bors r+

**Pull request merged**
