### PR TITLE
Updates for v0.3.x

### LINKED ISSUE #64: Unable to get gpio-cdev feature working on v0.3.0
As the title suggests, v0.3.0 of linux-embedded-hal does not have gpio-cdev feature, but it is claimed to have in the documentaiton.

### PR DESCRIPTION
**Pull request by eldruin**
Fixes #64

### CODE REVIEW

**Comment by eldruin** [comment]
Yeah, the MSRV is effectively broken due to the `bitflags` dependency. The MSRV is now actually 1.46.0.
I guess we have three alternatives here:
1. Raise MSRV and release 0.3.1. a.k.a. acknowledge status-quo
2. Raise MSRV and release this as 0.4.0. (0.3 stays broken. Weird for people using 0.4.0-alpha.0)
3. Do not release this: 0.3 stays broken until we publish 0.4, which may take a long time.

Given the current situation and that not a single issue has been opened due to the broken state of the MSRV, I would go with 1.

**Comment by nastevens** [comment]
@eldruin I agree - 1 seems like the most generally useful move.

**Comment by eldruin** [comment]
bors try

**Comment by eldruin** [comment]
The current state of this PR represents option 1 now and can be merged for a 0.3.1 release

**Review by ryankurte — APPROVED** [review]
:+1:

**Comment by eldruin** [comment]
bors r=ryankurte

**Pull request merged**
